name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with marp cli
        shell: bash
        run: |
          npx @marp-team/marp-cli src/index.md -o build/index.html
          npx @marp-team/marp-cli src/index.md -o build/slides.pdf
      - name: Copy images
        shell: bash
        run: |
          cp -r src/images build/images
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
  